apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  selector:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: rpsd
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
