apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rpsd

resources:
  - namespace.yaml
  - secrets.yaml
  # Messaging
  - kafka/
  - kafka-ui/
  - schema-registry/
  - rabbitmq/
  # Prefect
  - prefect-db/
  - prefect-redis/
  - prefect/
  # Keycloak
  - keycloak-db/
  - keycloak/
  # Config DB
  - config-db/
  # Application
  - rpsd-ingest/
  - rpsd-config/
  # Gateway API
  - gateway/
