# SPDX-FileCopyrightText: 2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Development-only defaults. For production (EKS), replace with
# ExternalSecrets, SealedSecrets, or a similar operator.
apiVersion: v1
kind: Secret
metadata:
  name: rpsd-secrets
type: Opaque
stringData:
  rpsd-keycloak-db-pass: "keycloak"
  rpsd-keycloak-admin-pass: "admin"
  rpsd-config-db-pass: "rpsd"
  rpsd-prefect-db-pass: "prefect"
  rpsd-rabbitmq-pass: "guest"
