apiVersion: v1
kind: Service
metadata:
  name: prefect-db
spec:
  selector:
    app.kubernetes.io/name: prefect-db
    app.kubernetes.io/part-of: rpsd
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
