apiVersion: v1
kind: Service
metadata:
  name: rpsd-ingest
spec:
  selector:
    app.kubernetes.io/name: rpsd-ingest
    app.kubernetes.io/part-of: rpsd
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
