services:
  postgis:
    image: ${RPSD_IMAGE_POSTGIS:-postgis/postgis:16-3.4}
    container_name: rpsd-postgis
    profiles: ["postgis", "database", "shared", "all"]
    environment:
      POSTGRES_DB: ${RPSD_POSTGIS_DB:-rpsd}
      POSTGRES_USER: ${RPSD_POSTGIS_USER:-rpsd}
      POSTGRES_PASSWORD: ${RPSD_POSTGIS_PASS:-rpsd}
    volumes:
      - rpsd-postgis-data:/var/lib/postgresql/data
      - ../shared/postgis/init.sql:/docker-entrypoint-initdb.d/01-postgis.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpsd"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${RPSD_POSTGIS_PORT:-5432}:5432"
    networks:
      - rpsd-network

volumes:
  rpsd-postgis-data:
    name: rpsd-postgis-data
