apiVersion: v1
kind: Service
metadata:
  name: prefect
spec:
  selector:
    app.kubernetes.io/name: prefect
    app.kubernetes.io/part-of: rpsd
  ports:
    - name: http
      port: 4200
      targetPort: 4200
  type: ClusterIP
