apiVersion: v1
kind: Service
metadata:
  name: prefect-redis
spec:
  selector:
    app.kubernetes.io/name: prefect-redis
    app.kubernetes.io/part-of: rpsd
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
